[package]
name = "ru_ratatui1"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6"
crossterm = "0.28"
ratatui = "0.29"

fakeit = "1.3.0"
itertools = "0.14.0"
unicode-width = "0.2.0"


[[bin]]
name = "table2"
path = "src/table2.rs"
